### ISSUE TITLE
Music and Pictures?

### ISSUE THREAD

**Issue by sanderklous** [ddurdle/XBMC-gdrive#1]
Off-topic:
This add-on works excellent for video, thanks a lot! I am running XBMC on my Ouya and this removes the need for an external hard drive. Also, it allows putting videos on my gdrive via a different machine and playing them via the Ouya.

On-topic:
How difficult is it to make the plugin work for pictures and music as well?
Thanks again,
Sander Klous

**Comment by ddurdle** [comment]
passed regression testing in 0.5.13; closing
