### ISSUE TITLE
Move to CloudService framework

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/XBMC-gdrive#16]
move to standard CloudService framework

**Comment by tysonedwards** [comment]
As you are likely aware, attempting to "Save STRM" on a folder that contains subfolders presently results in the new CloudService Script exiting with an error:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'title'
                                            Traceback (most recent call last):
                                              File "/Users/tysonedwards/Library/Application Support/Kodi/addons/XBMC-gdrive-unstable/default.py", line 362, in <module>
                                                service.buildSTRM(path + '/'+title,folderID)
                                              File "/Users/tysonedwards/Library/Application Support/Kodi/addons/XBMC-gdrive-unstable/resources/lib/cloudservice.py", line 125, in buildSTRM
                                                url = self.PLUGIN_URL+'?mode=video&title='+item.file.title+'&filename='+item.file.id
                                            AttributeError: 'NoneType' object has no attribute 'title'
                                            -->End of Python script error report<--

This looks like expected behavior at the moment due to the cloudservice.py not containing a handler for subfolder parsing, just elements in the present working directory.


Additionally, there appears to be a possible regression that was introduced somewhere in this latest commit, but as of yet I've been unable to locate where. When one attempts to use HEVC media, the new 0.5.0 unstable commit has broken playback, forcing default selection for the codec to an MP4 Transcode even though it doesn't exist server-side. Previously, it would utilize the Original File with this codec, as defined by the Google Drive API. When one enables "Force Manual Selection" within the settings menu and attempts to select an HEVC video file, no listings of codec or "Original" option will be presented, and the following entry will appear in the logs: 

19:39:03 T:140735139783424   ERROR: Control 3 in window 12000 has been asked to focus, but it can't

**Comment by ddurdle** [comment]
Thanks for the feedback.  Subfolder support should be included next, including ability to "flatten" the STRMs to a single directory.

Yes, I had same issue with non-transcodable videos.  The new version dropped the "original" stream.  Still determining how the url should be fetched. It looks like I'll have to make two web calls.

If you call streamvideo, it should still present the original stream option.

**Comment by ddurdle** [comment]
I think the issue is resolved.  Pushed out in 0.5.1.  

When I copied the procedure from another plugin, I forgot to change the line that determines if the object is only a folder (item.file is None).  When I made this change and tested, a directory of 3 subfolders deep generated the folders and .STRM files without issue.

Someone has contributed a change to flatten movies to a single folder and export STRMs for TV shows to show/season folder format.  Before adding this, I'll get some folks to test that subfolders is working.

**Comment by ddurdle** [comment]
You should be able to test by manually updating or updating using the testing repository http://dmdsoftware.net/repository.ddurdle-testing/repository.ddurdle-testing.zip

**Comment by ddurdle** [comment]
or here: http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.gdrive-testing/plugin.video.gdrive-testing-0.5.1.zip

**Comment by tysonedwards** [comment]
Yep, the nested folder issue appears solved.

Just had it generate streams of 1578 Episodes across 52 TV Shows that I have accessible on Google Drive.

For good measure I tested both of the following for you:

TV Shows/TV Show (Year)/TV Show (Year) - sNNeNN - Episode Name [Resolution].mkv
TV Shows/TV Show (Year)/Season Number/TV Show (Year) - sNNeNN - Episode Name [Resolution].mkv

Additionally I scanned a movie collection, however that was flat files in a single directory. That scanned successfully, as expected.

Movies/Movie [Year] [IMDB Code] [Resolution].mkv

That gives you a good test of 1 and 2 subfolders at least.

Additionally, Kodi scanned the collection and added it to the library, property identifying the episodes and mixing them with the Local Library, and verified that they could be selected through the PseudoTV Live Interface, TV Guide Interface, or the traditional Library view.

The HEVC Codec issue appears unresolved though, however considering your response below, I didn’t suspect that you’d had a chance to work on it just yet.

Tyson Edwards

**Comment by ddurdle** [comment]
I need to regression test the "original" stream option now that I changed the way it is retrieved.  It'll be ready shortly.

**Comment by ddurdle** [comment]
I was able to "stress" test the .STRM file creation.  It was actually an accident.  I was meaning to only perform it on a subfolder but accidentally had it generate for the entire google account.  

Finished without error, which is a huge laugh, because I have so many subdirectories, etc.  Each directory is an API call to google.

In total, the run generated 5235 STRMs.  There's no way in Google Drive to have it count and report the total number of files, but this probably looks around right :)
find . -type f -print| wc -l
5235


It is possible to tie in buildstrm with the "show all videos".  It would actually be more efficient as these videos are pulled in API batch calls of 100 units (so 56 calls in my case).  Otherwise, if you select a directory to build strms on, it traverses all the directories below through the Google API.  So in my case, 410 directories = at least 410 API calls

find . -type d -print| wc -l
410

**Comment by ddurdle** [comment]
passed regression testing in 0.5.13; closing
