### ISSUE TITLE
Subtitles Support on gdrive movies

### ISSUE THREAD

**Issue by piotrekcrash** [ddurdle/XBMC-gdrive#18]
gdrive is supporting to add subtitles to the videos.
Are You planning to add possibility to use these subtitles in XBMC/Kodi?

![image](https://cloud.githubusercontent.com/assets/8939242/5661302/836df12a-972a-11e4-8b77-edda3ce41f1b.png)

**Comment by ddurdle** [comment]
https://github.com/ddurdle/XBMC-gdrive/issues/10

**Comment by piotrekcrash** [comment]
Sorry for duplicate. Please Remove my Issue to keep clean. Thanks
