### ISSUE TITLE
Faulty Character encoding for Folders (Save STRM)

### ISSUE THREAD

**Issue by cappa83** [ddurdle/XBMC-gdrive#19]
```\Deadwood\Staffel 2\Deadwood - S02E01 - LebenslÃ¼ge (1).avi.strm``` works

14:28:11 T:2288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IOError'>
Error Contents: (2, 'No such file or directory', 'C:\\Datenbank\\/Erwachsene/CSI Den T\xc3\xa4tern auf der Spur/Staffel 13\\CSI Den T\xc3\xa4tern auf der Spur - S13E07 - Warricks Familie.mkv.strm')
Traceback (most recent call last):
File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\default.py", line 364, in <module>
service.buildSTRM(path + '/'+title,folderID)
File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 117, in buildSTRM
self.buildSTRM(path + '/'+item.folder.title, item.folder.id)
File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 117, in buildSTRM
self.buildSTRM(path + '/'+item.folder.title, item.folder.id)
File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 127, in buildSTRM
strmFile = open(filename, "w")
IOError: (2, 'No such file or directory', 'C:\\Datenbank\\/Erwachsene/CSI Den T\xc3\xa4tern auf der Spur/Staffel 13\\CSI Den T\xc3\xa4tern auf der Spur - S13E07 - Warricks Familie.mkv.strm')
-->End of Python script error report<--

So it seems to be a Problem if a german character is in directoryname. A äöü in Filename doesn't break the script.

Is there a short solution for this? (haven't tried it on my Raspberry for now, only on my windows box)

**Comment by ddurdle** [comment]
The xbmcvfs mkdir must be failing and doesn't like the characters.  We
don't use xbmcvfs to write the files, so if a file contains the characters,
it is created successfully.

On Saturday, January 17, 2015, cappa83 <notifications@github.com> wrote:

> \Deadwood\Staffel 2\Deadwood - S02E01 - LebenslÃ¼ge (1).avi.strm works
>
> ```ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python
> callback/script returned the following error<--
>
>                                          - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>
>                                         Error Type: <type 'exceptions.IOError'>
>                                         Error Contents: (2, 'No such file or directory', 'C:\\Datenbank\\/Erwachsene/CSI Den T\xc3\xa4tern auf der Spur/Staffel 13\\CSI Den T\xc3\xa4tern auf der Spur - S13E07 - Warricks Familie.mkv.strm')
>
>                                         Traceback (most recent call last):
>
>                                           File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\default.py", line 364, in <module>
>
>                                             service.buildSTRM(path + '/'+title,folderID)
>
>                                           File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 117, in buildSTRM
>
>                                             self.buildSTRM(path + '/'+item.folder.title, item.folder.id)
>
>                                           File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 117, in buildSTRM
>
>                                             self.buildSTRM(path + '/'+item.folder.title, item.folder.id)
>                                           File "C:\Users\XXX\AppData\Roaming\Kodi\addons\XBMC-gdrive-unstable\resources\lib\cloudservice.py", line 127, in buildSTRM
>
>                                             strmFile = open(filename, "w")
>
>                                         IOError: (2, 'No such file or directory', 'C:\\Datenbank\\/Erwachsene/CSI Den T\xc3\xa4tern auf der Spur/Staffel 13\\CSI Den T\xc3\xa4tern auf der Spur - S13E07 - Warricks Familie.mkv.strm')
>                                         -->End of Python script error report<--```
>
> So it seems to be a Problem if a german character is in directoryname. A
> äöü in Filename doesn't break the script.
>
> Is there a short solution for this? (haven't tried it on my Raspberry for
> now, only on my windows box)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddurdle/XBMC-gdrive/issues/19>.
>


-- 
Sent from iPhone

**Comment by cappa83** [comment]
Nah, the files are created successfully. Only if a directory(!) contains a äöü it is failing with this error.

The mkdir works :-) Only if a file should be written into that dir it's failing.

In my example the directory C:\Datenbank\Erwachsene\CSI Den Tätern auf der Spur\Staffel 13\ is existing after that error.

**Comment by ddurdle** [comment]
I see, interesting.  Should be easy to fix then :)

**Comment by cappa83** [comment]
If I see it correctly, the folder is written in correct UTF-8 "CSI Den Tätern auf der Spur" but then searched in wrong encoding "CSI Den T\xc3\xa4tern auf der Spur"

The folders are correct and the fileencoding seems to be broken "Cougar Town - S04E03 - SuperkrÃ¤fte.mkv.strm"

Not an error for me, if all strms are written :-D

**Comment by ddurdle** [comment]
Since 0.5.10, I've moved to using xbmcvfs for writing all folders.  This issue should be working.  Can you try?
