### ISSUE TITLE
FLAC files not listed

### ISSUE THREAD

**Issue by rindeal** [ddurdle/XBMC-gdrive#43]
FLAC files are not listed not even when "List everything" is enabled. Using latest git revision and latest KODI.

**Comment by ddurdle** [comment]
Are they showing up with Music only?

**Comment by ddurdle** [comment]
I'm not able to reproduce the issue.  Can you please elaborate?

When I go into KODI->MUSIC, for both "Everything" and "Music only", I see my flac files listed, and they playback.

Can you also confirm if your flac files show up with the "audio" icon in Google Drive Web App?  Although Google Drive doesn't playback flac files, they'll still classify them as music files.  At one time, Google Drive would classify them as unknown.

**Comment by rindeal** [comment]
Thank you for your prompt response. For me they are listed neither with "Everything" nor with "Music only". I can provide you some important parts of API response:
```json
appDataContents: false
copyable: true
fileExtension: "flac"
iconLink: "https://ssl.gstatic.com/docs/doclist/images/generic_app_icon_16.png"
kind: "drive#file"
mimeType: "application/x-flac"
originalFilename: "xxxxxxxxxxxxxx.flac"
title: "xxxxxxxxxxxxxx.flac"
```
As you can see from the response, Google Drive Web App should show generic app icon.

Also I don't quite understand your decision not to use [the official Google API Client](https://github.com/google/google-api-python-client) and use XML and RegEx instead... It must greatly reduce maintainability and robustness.

**Comment by ddurdle** [comment]
Somehow your audio files are being categorized as application files (application/x-flac) instead of audio (audio/x-flac).  I'll add this to the audio list.  It will be in tonight's release.

From my account:
                                               "iconLink": "https://ssl.gstatic.com/docs/doclist/images/generic_app_icon_16.png",
                                               "title": "Bob Guiney - 3 Sides - 07 - Craziest Girl I Know.flac",
                                               "mimeType": "audio/x-flac",
                                               "originalFilename": "Bob Guiney - 3 Sides - 07 - Craziest Girl I Know.flac",
                                               "fileExtension": "flac",

**Comment by rindeal** [comment]
It works. Thank you very much.

I assume the API response dumps in the KODI log file can now be removed.

**Comment by niemasd** [comment]
I am having the same issue: FLAC files are not showing up. Perhaps an update you performed at some point reverted the fix?
